package local.test.model.modules;

import oracle.jbo.server.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jul 21 08:43:05 BST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NovoAppModuleImpl extends ApplicationModuleImpl {
 /**
  * This is the default constructor (do not remove).
  */
 public NovoAppModuleImpl() {
 }
}

